language: bash
services: docker

before_script:
  - cp settings.xml maven-jdk11
  - cp settings.xml maven-jdk8
  - cp settings.xml gradle-jdk11
  - cp settings.xml gradle-jdk8
  - cp settings.xml maven-gradle-docker-jdk13

script:
  - docker build -t fabricio20/jenkins-nodes:maven-gradle-docker-jdk13 maven-gradle-docker-jdk13
  - bash docker_push.sh
  - docker build -t fabricio20/jenkins-nodes:maven-jdk11 maven-jdk11
  - docker build -t fabricio20/jenkins-nodes:maven-jdk8 maven-jdk8
  - docker build -t fabricio20/jenkins-nodes:gradle-jdk11 gradle-jdk11
  - docker build -t fabricio20/jenkins-nodes:gradle-jdk8 gradle-jdk8

deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: master
